[opener]
edit = [
    # { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
   # { run = 'lvim "$@"', desc = "lvim", block = true, for = "unix" },
    { run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
    { run = 'code %*', orphan = true, desc = "code", for = "windows" },
    { run = 'code -w %*', block = true, desc = "code (block)", for = "windows" },
]
